### PR TITLE
Added some plugins =)

### PR DESCRIPTION
**Pull request by Tanguygab**
Incompatibilities
 - TabooLib
Compatibilities:
 - TAB (free+premium)
 - PlaceholderAPI
 - LuckPerms

### CODE REVIEW

**Comment by kwright02** [comment]
please change placeholderapi to a .library since it is just an api

**Comment by Tanguygab** [comment]
oki, it still is a plugin I guess but yeah I wasn't sure what would fit better, 2m

**Comment by Tanguygab** [comment]
done

**Comment by kwright02** [comment]
Sorry I didn't notice this earlier, but please also rename taboolib.plugin.library to taboolib.library.incompstible

**Comment by Tanguygab** [comment]
oki I will once I get on my pc, but shouldn't it be fine if I put it into the Incompatible folder?

**Pull request merged**
